%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Volumes/KvanHeusden/Klaske Work Files/COVID19/models/Files Paper for Publication/BCVaccinationprogress.csv
%
% Auto-generated by MATLAB on 21-Jul-2021 12:45:46

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["week_end", "prename", "proptotal_atleast1dose", "weeklyrate"];
opts.VariableTypes = ["datetime", "categorical", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "prename", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "week_end", "InputFormat", "yyyy-MM-dd");

% Import the data
BCVaccinationprogress = readtable("BCVaccinationprogress.csv", opts);


%% Clear temporary variables
clear opts